title = 'Docura'
baseURL = 'https://cevtuocjw.github.io/LOGcevtuoUO//'

defaultContentLanguage = 'en'
languageCode = 'en-us'

enableGitInfo = true

markup.highlight.noClasses = false

[services]
[services.googleAnalytics]
ID = 'G-XXXXXXXXXX'