name = "Docura"
license = "MIT"
licenselink = ""
description = "A modular Hugo theme for your next documentation site"
homepage = "https://cevtuocjw.github.io/LOGcevtuoUO/"
demosite = "https://docura.github.io"
tags = ["documentation", "responsive", "dark mode", "light mode", "modern", "clean", "customizable"]
features = ["responsive", "customizable", "dark mode", "light mode", "night mode", "search", "syntax highlighting", "multilingual", "seo", "docsearch"]
min_version = "0.41.0"

[author]
  name = "cjw"
  homepage = "cevtuogrnd.com"
